package detect

var (
	// PlatFormKeys is platform keys
	PlatFormKeys = map[int]string{
		0:  "windows nt 10.0",
		1:  "windows nt 6.3",
		2:  "windows nt 6.2",
		3:  "windows nt 6.1",
		4:  "windows nt 6.0",
		5:  "windows nt 5.2",
		6:  "windows nt 5.1",
		7:  "windows nt 5.0",
		8:  "windows nt 4.0",
		9:  "winnt4.0",
		10: "winnt 4.0",
		11: "winnt",
		12: "windows 98",
		13: "win98",
		14: "windows 95",
		15: "win95",
		16: "windows phone",
		17: "windows",
		18: "android",
		19: "blackberry",
		20: "iphone",
		21: "ipad",
		22: "ipod",
		23: "os x",
		24: "ppc mac",
		25: "freebsd",
		26: "ppc",
		27: "linux",
		28: "debian",
		29: "sunos",
		30: "beos",
		31: "apachebench",
		32: "aix",
		33: "irix",
		34: "osf",
		35: "hp-ux",
		36: "netbsd",
		37: "bsdi",
		38: "openbsd",
		39: "gnu",
		40: "unix",
		41: "symbian",
	}

	// PlatForms for user agent
	PlatForms = map[string]string{
		"windows nt 10.0": "Windows 10",
		"windows nt 6.3":  "Windows 8.1",
		"windows nt 6.2":  "Windows 8",
		"windows nt 6.1":  "Windows 7",
		"windows nt 6.0":  "Windows Vista",
		"windows nt 5.2":  "Windows 2003",
		"windows nt 5.1":  "Windows XP",
		"windows nt 5.0":  "Windows 2000",
		"windows nt 4.0":  "Windows NT 4.0",
		"winnt4.0":        "Windows NT 4.0",
		"winnt 4.0":       "Windows NT",
		"winnt":           "Windows NT",
		"windows 98":      "Windows 98",
		"win98":           "Windows 98",
		"windows 95":      "Windows 95",
		"win95":           "Windows 95",
		"windows phone":   "Windows Phone",
		"windows":         "Unknown Windows OS",
		"android":         "Android",
		"blackberry":      "BlackBerry",
		"iphone":          "iOS",
		"ipad":            "iOS",
		"ipod":            "iOS",
		"os x":            "Mac OS X",
		"ppc mac":         "Power PC Mac",
		"freebsd":         "FreeBSD",
		"ppc":             "Macintosh",
		"linux":           "Linux",
		"debian":          "Debian",
		"sunos":           "Sun Solaris",
		"beos":            "BeOS",
		"apachebench":     "ApacheBench",
		"aix":             "AIX",
		"irix":            "Irix",
		"osf":             "DEC OSF",
		"hp-ux":           "HP-UX",
		"netbsd":          "NetBSD",
		"bsdi":            "BSDi",
		"openbsd":         "OpenBSD",
		"gnu":             "GNU/Linux",
		"unix":            "Unknown Unix OS",
		"symbian":         "Symbian OS",
	}

	// Browsers for user agent
	Browsers = map[string]string{
		"OPR":               "Opera",
		"Flock":             "Flock",
		"Edge":              "Spartan",
		"Chrome":            "Chrome",
		"Opera.*?Version":   "Opera",
		"Opera":             "Opera",
		"MSIE":              "Internet Explorer",
		"Internet Explorer": "Internet Explorer",
		"Trident.* rv":      "Internet Explorer",
		"Shiira":            "Shiira",
		"Firefox":           "Firefox",
		"Chimera":           "Chimera",
		"Phoenix":           "Phoenix",
		"Firebird":          "Firebird",
		"Camino":            "Camino",
		"Netscape":          "Netscape",
		"OmniWeb":           "OmniWeb",
		"Safari":            "Safari",
		"Mozilla":           "Mozilla",
		"Konqueror":         "Konqueror",
		"icab":              "iCab",
		"Lynx":              "Lynx",
		"Links":             "Links",
		"hotjava":           "HotJava",
		"amaya":             "Amaya",
		"IBrowse":           "IBrowse",
		"Maxthon":           "Maxthon",
		"Ubuntu":            "Ubuntu Web Browser",
		"Vivaldi":           "Vivaldi",
	}

	// Mobiles for user agent
	Mobiles = map[string]string{
		"mobileexplorer": "Mobile Explorer",
		"palmsource":     "Palm",
		"palmscape":      "Palmscape",
		// Phones and Manufacturers
		"motorola":             "Motorola",
		"nokia":                "Nokia",
		"palm":                 "Palm",
		"iphone":               "Apple iPhone",
		"ipad":                 "iPad",
		"ipod":                 "Apple iPod Touch",
		"sony":                 "Sony Ericsson",
		"ericsson":             "Sony Ericsson",
		"blackberry":           "BlackBerry",
		"cocoon":               "O2 Cocoon",
		"blazer":               "Treo",
		"lg":                   "LG",
		"amoi":                 "Amoi",
		"xda":                  "XDA",
		"mda":                  "MDA",
		"vario":                "Vario",
		"htc":                  "HTC",
		"samsung":              "Samsung",
		"sharp":                "Sharp",
		"sie-":                 "Siemens",
		"alcatel":              "Alcatel",
		"benq":                 "BenQ",
		"ipaq":                 "HP iPaq",
		"mot-":                 "Motorola",
		"playstation portable": "PlayStation Portable",
		"playstation 3":        "PlayStation 3",
		"playstation vita":     "PlayStation Vita",
		"hiptop":               "Danger Hiptop",
		"nec-":                 "NEC",
		"panasonic":            "Panasonic",
		"philips":              "Philips",
		"sagem":                "Sagem",
		"sanyo":                "Sanyo",
		"spv":                  "SPV",
		"zte":                  "ZTE",
		"sendo":                "Sendo",
		"nintendo dsi":         "Nintendo DSi",
		"nintendo ds":          "Nintendo DS",
		"nintendo 3ds":         "Nintendo 3DS",
		"wii":                  "Nintendo Wii",
		"open web":             "Open Web",
		"openweb":              "OpenWeb",
		// Operating Systems
		"android":    "Android",
		"symbian":    "Symbian",
		"SymbianOS":  "SymbianOS",
		"elaine":     "Palm",
		"series60":   "Symbian S60",
		"windows ce": "Windows CE",
		// Browsers
		"obigo":         "Obigo",
		"netfront":      "Netfront Browser",
		"openwave":      "Openwave Browser",
		"mobilexplorer": "Mobile Explorer",
		"operamini":     "Opera Mini",
		"opera mini":    "Opera Mini",
		"opera mobi":    "Opera Mobile",
		"fennec":        "Firefox Mobile",
		// Other
		"digital paths": "Digital Paths",
		"avantgo":       "AvantGo",
		"xiino":         "Xiino",
		"novarra":       "Novarra Transcoder",
		"vodafone":      "Vodafone",
		"docomo":        "NTT DoCoMo",
		"o2":            "O2",
		// Fallback
		"mobile":     "Generic Mobile",
		"wireless":   "Generic Mobile",
		"j2me":       "Generic Mobile",
		"midp":       "Generic Mobile",
		"cldc":       "Generic Mobile",
		"up.link":    "Generic Mobile",
		"up.browser": "Generic Mobile",
		"smartphone": "Generic Mobile",
		"cellphone":  "Generic Mobile",
	}

	// Robots for search bot
	Robots = map[string]string{
		"googlebot":            "Googlebot",
		"msnbot":               "MSNBot",
		"baiduspider":          "Baiduspider",
		"bingbot":              "Bing",
		"slurp":                "Inktomi Slurp",
		"yahoo":                "Yahoo",
		"ask jeeves":           "Ask Jeeves",
		"fastcrawler":          "FastCrawler",
		"infoseek":             "InfoSeek Robot 1.0",
		"lycos":                "Lycos",
		"yandex":               "YandexBot",
		"mediapartners-google": "MediaPartners Google",
		"CRAZYWEBCRAWLER":      "Crazy Webcrawler",
		"adsbot-google":        "AdsBot Google",
		"feedfetcher-google":   "Feedfetcher Google",
		"curious george":       "Curious George",
		"ia_archiver":          "Alexa Crawler",
		"MJ12bot":              "Majestic-12",
		"Uptimebot":            "Uptimebot",
	}
)
